cars = ['bmw', 'audi', 'toyota', 'subaru']
# cars.sort()
# print(cars)
# cars.sort(reverse=True)
# print(cars)
print("\nHere is the sorted list:")
print(sorted(cars))
cars.reverse()
print(cars)
print(len(cars))